### ISSUE TITLE
Result on KAIST Urban16 dataset

### ISSUE THREAD

**Issue by 673402618** [CAOR-MINES-ParisTech/lwoi#3]
The left picture is the result trajectory in the paper. The right one is the trajectory on the github. Why do they look different?
![1664000405](https://user-images.githubusercontent.com/35944071/56885950-6ac33380-6aa0-11e9-8114-d869dd60654f.jpg)

**Comment by mbrossar** [comment]
The scale for the x and the y axis are different between the two images. This explain why the second image is enlarged.
I think you wonder why the green results on the left seem to be better than on the right. This is the two main reasons: the left picture is based on a slightly more complex code that rejects big outliers from wheels, whereas the right image is based on the simplified code of this repo. And very importantly, the method was learned twice: one for the paper and one for the repo. Since learning is stochastic, final results differ.
